<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="250" started-at="2016-01-31T15:36:48Z" finished-at="2016-01-31T15:36:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="250" started-at="2016-01-31T15:36:48Z" finished-at="2016-01-31T15:36:49Z">
      <class name="org.chapter01.hibernate.PersistenceTest">
        <test-method status="FAIL" signature="setup()[pri:0, instance:org.chapter01.hibernate.PersistenceTest@2c7614d6]" name="setup" is-config="true" duration-ms="0" started-at="2016-01-31T17:36:48Z" finished-at="2016-01-31T17:36:48Z">
          <exception class="org.hibernate.MappingException">
            <message>
              <![CDATA[Unable to load class [ chapter01.hibernate.Message] declared in Hibernate configuration <mapping/> entry]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.MappingException: Unable to load class [ chapter01.hibernate.Message] declared in Hibernate configuration <mapping/> entry
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2219)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2167)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2147)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2100)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2015)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1994)
	at org.chapter01.hibernate.PersistenceTest.setup(PersistenceTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.ClassNotFoundException: chapter01.hibernate.Message
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
	at org.hibernate.internal.util.ReflectHelper.classForName(ReflectHelper.java:192)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2216)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.MappingException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="saveMessage()[pri:0, instance:org.chapter01.hibernate.PersistenceTest@2c7614d6]" name="saveMessage" duration-ms="0" started-at="2016-01-31T17:36:49Z" finished-at="2016-01-31T17:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveMessage -->
        <test-method status="SKIP" signature="readMessage()[pri:0, instance:org.chapter01.hibernate.PersistenceTest@2c7614d6]" name="readMessage" duration-ms="0" started-at="2016-01-31T17:36:49Z" depends-on-methods="org.chapter01.hibernate.PersistenceTest.saveMessage" finished-at="2016-01-31T17:36:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PersistenceTest.readMessage()[pri:0, instance:org.chapter01.hibernate.PersistenceTest@2c7614d6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PersistenceTest.readMessage()[pri:0, instance:org.chapter01.hibernate.PersistenceTest@2c7614d6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readMessage -->
      </class> <!-- org.chapter01.hibernate.PersistenceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
