<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="6" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1285" started-at="2016-02-14T18:59:53Z" finished-at="2016-02-14T18:59:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1285" started-at="2016-02-14T18:59:53Z" finished-at="2016-02-14T18:59:54Z">
      <class name="org.chapter00_util.JPA.JPASessionUtilTest">
        <test-method status="PASS" signature="getEntityManager()[pri:0, instance:org.chapter00_util.JPA.JPASessionUtilTest@664bb5d8]" name="getEntityManager" duration-ms="1081" started-at="2016-02-14T20:59:53Z" finished-at="2016-02-14T20:59:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEntityManager -->
        <test-method status="PASS" signature="getSession()[pri:0, instance:org.chapter00_util.JPA.JPASessionUtilTest@664bb5d8]" name="getSession" duration-ms="1" started-at="2016-02-14T20:59:54Z" finished-at="2016-02-14T20:59:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSession -->
        <test-method status="PASS" signature="nonexistentEntityManagerName()[pri:0, instance:org.chapter00_util.JPA.JPASessionUtilTest@664bb5d8]" name="nonexistentEntityManagerName" duration-ms="19" started-at="2016-02-14T20:59:54Z" finished-at="2016-02-14T20:59:54Z">
          <exception class="javax.persistence.PersistenceException">
            <message>
              <![CDATA[No Persistence provider for EntityManager named nonexistent]]>
            </message>
            <full-stacktrace>
              <![CDATA[javax.persistence.PersistenceException: No Persistence provider for EntityManager named nonexistent
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:69)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
	at org.chapter00_util.JPA.JPASessionUtil.getEntityManager(JPASessionUtil.java:18)
	at org.chapter00_util.JPA.JPASessionUtilTest.nonexistentEntityManagerName(JPASessionUtilTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- javax.persistence.PersistenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonexistentEntityManagerName -->
        <test-method status="PASS" signature="nonexistentSessionName()[pri:0, instance:org.chapter00_util.JPA.JPASessionUtilTest@664bb5d8]" name="nonexistentSessionName" duration-ms="15" started-at="2016-02-14T20:59:54Z" finished-at="2016-02-14T20:59:54Z">
          <exception class="javax.persistence.PersistenceException">
            <message>
              <![CDATA[No Persistence provider for EntityManager named nonexistent]]>
            </message>
            <full-stacktrace>
              <![CDATA[javax.persistence.PersistenceException: No Persistence provider for EntityManager named nonexistent
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:69)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
	at org.chapter00_util.JPA.JPASessionUtil.getEntityManager(JPASessionUtil.java:18)
	at org.chapter00_util.JPA.JPASessionUtil.getSession(JPASessionUtil.java:24)
	at org.chapter00_util.JPA.JPASessionUtilTest.nonexistentSessionName(JPASessionUtilTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- javax.persistence.PersistenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonexistentSessionName -->
        <test-method status="PASS" signature="testEntityManager()[pri:0, instance:org.chapter00_util.JPA.JPASessionUtilTest@664bb5d8]" name="testEntityManager" duration-ms="141" started-at="2016-02-14T20:59:54Z" finished-at="2016-02-14T20:59:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEntityManager -->
        <test-method status="PASS" signature="testSession()[pri:0, instance:org.chapter00_util.JPA.JPASessionUtilTest@664bb5d8]" name="testSession" duration-ms="5" started-at="2016-02-14T20:59:54Z" finished-at="2016-02-14T20:59:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSession -->
      </class> <!-- org.chapter00_util.JPA.JPASessionUtilTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
